services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: dating
    ports:
      - "5432:5432"
